### ISSUE TITLE
ERROR TRACEBACK: ModuleNotFoundError: No Module named 'sklearn'

### ISSUE THREAD

**Issue by Bacoom** [raganmd/touchdesigner-dominant-color#9]
![Screenshot 2024-04-14 233232](https://github.com/raganmd/touchdesigner-dominant-color/assets/167037158/19b8cb4c-1e67-466b-ad17-e364671264cb)

Hi Mathew, I'm trying to use you dominant colour system. It looks great and cant wait to start using. 

I'm really struggling though :( I'm positive i've correctly installed on Python 3.5.4. I can see the 'sklearn' folder within my 'site-packages'. Also the Python tab in the base doesn't appear in the custom components. Any advice or help would be much appreciated.

 I'm a novice to this python TD stuff.

**Comment by raganmd** [comment]
There are a healthy bit of changes to the Python environment for Touch since I made this component. I'll check with the latest stable to see what might be happening there.

**Comment by Bacoom** [comment]
Thanks Mathew! Legend!

**Comment by raganmd** [comment]
One quick note here having doing a little preliminary look. Numpy now ships with Touch, so part of the issue is coming back to numpy versioning. There's also been significant updates to TD in the last several years, so rather than just patching this I'm going to look at what a more modern approach might look like with some of the changes to how TD runs.

**Comment by raganmd** [comment]
@Bacoom - there's an update here that's worth checking out. You should now be able to download the TOX from /releases and give this another test. I've currently only tested this on windows (my primary dev platform). A few important steps.

1. first create a directory to save you project in.
2. open TouchDesigner and save your project file in that directory - the tox will download some python libraries and it needs to the project to be saved before it can do that
3. drag and drop the tox into your network
4. you should see a terminal window open and download some python
5. when download completes you may need to bypass and unbypass the comp, or reinit the extension

There are a few other testing pieces I need to do here, and some other cleanup but this should now at least be working as expected.

**Comment by raganmd** [comment]
@Bacoom there's been one more push that should reduce the number of times that the TOX will try to install any libraries it needs. This should now only happen the first time you install the TOX.

**Comment by Bacoom** [comment]
Hey Mathew, Just been playing with it today! it works great! Thanks so much for fixing this, really appreciate it. I've now started reading and watching through a couple of your Python TD intros. Your a legend! wish me luck

**Comment by raganmd** [comment]
@Bacoom - so glad this is working for you! You'll be great - feel free to hit me up on that reddit thread if you get stuck.
